
version: '3.3'
services:
  web:
    build:
      context: ./WebPage
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./WebPage:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: mysqldb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ANPR
      MYSQL_USER: chris
      MYSQL_PASSWORD: chrispass
      MYSQL_LOCAL_INFILE: 1
    volumes:
      - ./ProcessedData/:/data/
    ports:
      - "6033:3306"
